-- SQL Seed File for Raags and Tags in Supabase
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Seed Raags (56 items)
INSERT INTO public.raags (name) VALUES
    ('Yaman'),
    ('Bhairav'),
    ('Bhairavi'),
    ('Bilawal'),
    ('Kafi'),
    ('Khamaj'),
    ('Asavari'),
    ('Todi'),
    ('Marwa'),
    ('Purvi'),
    ('Kedar'),
    ('Bageshri'),
    ('Malkauns'),
    ('Darbari Kanada'),
    ('Desh'),
    ('Brindavani Sarang'),
    ('Shivranjani'),
    ('Pahadi'),
    ('Bhupali'),
    ('Hamsadhwani'),
    ('Ahir Bhairav'),
    ('Jog'),
    ('Jogiya'),
    ('Jaijaiwanti'),
    ('Jhinjhoti'),
    ('Tilak Kamod'),
    ('Rageshri'),
    ('Shuddh Kalyan'),
    ('Alhaiya Bilawal'),
    ('Gaud Sarang'),
    ('Madhmad Sarang'),
    ('Multani'),
    ('Miyan Ki Todi'),
    ('Gujari Todi'),
    ('Shree'),
    ('Lalit'),
    ('Basant'),
    ('Hindol'),
    ('Bahar'),
    ('Ramkali'),
    ('Deshkar'),
    ('Pilu'),
    ('Sindhu Bhairavi'),
    ('Megh'),
    ('Miyan Ki Malhar'),
    ('Maru Bihag'),
    ('Bihag'),
    ('Chhayanat'),
    ('Shankara'),
    ('Adana'),
    ('Megh Malhar'),
    ('Gaud Malhar'),
    ('Sur Malhar'),
    ('Tilang'),
    ('Mand'),
    ('Gara')
ON CONFLICT (name) DO NOTHING;

-- 2. Seed Tags (67 items)
INSERT INTO public.tags (name) VALUES
    ('Gujarati Folk'),
    ('Gujarati Lokgeet'),
    ('Lokgeet'),
    ('Garba'),
    ('Dayro'),
    ('Dandiya'),
    ('Raas'),
    ('Bhajan'),
    ('Santvani'),
    ('Duha'),
    ('Chhand'),
    ('Maa No Garbo'),
    ('Lagna Geet'),
    ('Lagna Lokgeet'),
    ('Halardu'),
    ('Lori'),
    ('Virah Geet'),
    ('Prem Geet'),
    ('Bhakti Geet'),
    ('Desi Geet'),
    ('Folk Bhajan'),
    ('Sufi Folk'),
    ('Charani Geet'),
    ('Raas Garba'),
    ('Navratri'),
    ('Janmashtami'),
    ('Ramdevpir'),
    ('Krishna'),
    ('Ram'),
    ('Shiv'),
    ('Mataji'),
    ('Amba Maa'),
    ('Bahuchar Maa'),
    ('Meldi Maa'),
    ('Khodiyar Maa'),
    ('Hinglaj Maa'),
    ('Chamunda Maa'),
    ('Ashapura Maa'),
    ('Pabuji'),
    ('Rann Utsav'),
    ('Kutchi Folk'),
    ('Saurashtra Folk'),
    ('Kathiyawadi'),
    ('Charotar'),
    ('Kutch'),
    ('Saurashtra'),
    ('North Gujarat'),
    ('South Gujarat'),
    ('Gujarati Traditional'),
    ('Traditional'),
    ('Cultural'),
    ('Village Folk'),
    ('Desi'),
    ('Devotional'),
    ('Spiritual'),
    ('Romantic'),
    ('Emotional'),
    ('Festive'),
    ('Energetic'),
    ('Melancholic'),
    ('Celebration'),
    ('Wedding'),
    ('Monsoon'),
    ('Love'),
    ('Virah'),
    ('Devotion')
ON CONFLICT (name) DO NOTHING;
