// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc9PO0hei9AJNuaxgHwrxXEVnCGX834eU',
    appId: '1:358451101596:web:3097147f8f5bbec5295259',
    messagingSenderId: '358451101596',
    projectId: 'lyri-8d380',
    authDomain: 'lyri-8d380.firebaseapp.com',
    storageBucket: 'lyri-8d380.firebasestorage.app',
    measurementId: 'G-G2CC6172RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRang_mL26dZ21d8LiAcNZMadQhkVmdI',
    appId: '1:358451101596:android:a4be106b7c2ea2b7295259',
    messagingSenderId: '358451101596',
    projectId: 'lyri-8d380',
    storageBucket: 'lyri-8d380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEfWRaxePzRagjpqlX5ATb5PAaQ7oLzE',
    appId: '1:358451101596:ios:4a534a828c695cca295259',
    messagingSenderId: '358451101596',
    projectId: 'lyri-8d380',
    storageBucket: 'lyri-8d380.firebasestorage.app',
    iosBundleId: 'com.example.lyriWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEfWRaxePzRagjpqlX5ATb5PAaQ7oLzE',
    appId: '1:358451101596:ios:4a534a828c695cca295259',
    messagingSenderId: '358451101596',
    projectId: 'lyri-8d380',
    storageBucket: 'lyri-8d380.firebasestorage.app',
    iosBundleId: 'com.example.lyriWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc9PO0hei9AJNuaxgHwrxXEVnCGX834eU',
    appId: '1:358451101596:web:c7b11ccd6cf052b3295259',
    messagingSenderId: '358451101596',
    projectId: 'lyri-8d380',
    authDomain: 'lyri-8d380.firebaseapp.com',
    storageBucket: 'lyri-8d380.firebasestorage.app',
    measurementId: 'G-28LM3NW1GQ',
  );
}
